### PR TITLE
galaxy test

### PR DESCRIPTION
**Pull request by hiiamboris**
My play with particle effects take two.

What I wanted initially is to rotate the whole canvas, and also rotate the emitter itself in the opposite direction so it would seed it with stars. Emitter rotation doesn't seem to be possible.

I also wanted emitter to be round, not box-shaped. Not possible.
Or alternatively emit in a line segment but with higher probability near the center of the segment, also not possible.

Also I wanted to pre-render first ~60 seconds of this, so the first frame would already be pre-populated with stars. `start -60` however doesn't seem to do anything different than `start 0` with relation to effects.

All that didn't work, so I had use speed for rotation and get tricky with `limits` to make emitter continuously emit something, not everything at once. Still went crappy :) For proper tangential rotation I would need to know particle distance to the center, otherwise they all rotate around different centers, relative to the emitted coordinate.

Note that last frame is cleared despite that no `expires` command is set.

### CODE REVIEW

**Comment by hiiamboris** [comment]
It's probably possible to re-emit all particles during the first second using respawn mechanics, which would open new possibilities, but I didn't explore it further.

**Comment by GalenIvanov** [comment]
I had a circular emitter too at first, but decided to keep only rectangular. I now see that it can bu useful, so will definately add it. Or maybe it's better to allow parametric approach, as for `limits`?
About emitting particles with higher probabilty near the center - isn't it possible to use something like my `motes` example?

```
new-coords: [
        t: random 4
        either t < 3 [
            x: 150.0
            y: 50.0 + random 300.0
        ][
            x: 50 + random 100.0
            y: 50.0
        ]
    ]
```

**Comment by GalenIvanov** [comment]
@hiiamboris I agree with you that forces need to know particle's position - I'll add it.

**Comment by hiiamboris** [comment]
I'm for everything as general as possible :) Emitter - a function, absorber - a function, particle - an object (if possible). But right now I'm just giving you enough food for thought. Once you solidify the design a bit, I'll come with more concrete enhancement proposals :)

**Comment by GalenIvanov** [comment]
Please have mercy, @hiiamboris ! :)

**Pull request merged**
